#!/bin/sh
. /lib/functions.sh

start_xunlei(){
	uci set xunlei.config.drive="$device"
	uci commit xunlei
	/etc/init.d/xunlei restart
}

stop_xunlei(){
	uci set xunlei.config.drive=""
	uci commit xunlei
	killall ETMDaemon
	killall EmbedThunderManager
	killall vod_httpserver
}

device=`basename $DEVPATH`

case "$ACTION" in
	add)
	
       case "$device" in
                sd*) ;;
                md*) ;;
                hd*);;     
                mmcblk*);;  
                *) return;;
        esac   
        
	mountpoint=`sed -ne "s|^[^ ]*/$device ||; T; s/ .*//p" /proc/self/mounts`
	have_path=$(uci show xunlei | grep -c "$mountpoint")
	[ "$have_path" -gt "0" ] && start_xunlei
	;;
	remove)
	have_device=$(uci show xunlei | grep -c "$device")
	[ "$have_device" -gt "0" ] && stop_xunlei
	;;
esac
