#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@domainlist[-1]
	add ucitrack domainlist
	set ucitrack.@domainlist[-1].init=domainlist
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
