#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=95
STOP=15
USE_PROCD=1

start_instance() {
	config_get_bool enabled $1 enabled 0
	config_get local_port $1 local_port
	config_get remote_ip $1 remote_ip
	config_get remote_port $1 remote_port
	config_get_bool allow_wan $1 allow_wan 0

	[ $enabled -eq 0 ] && return 0

	procd_open_instance
	procd_set_param command /usr/bin/mproxy -T -l $local_port -h $remote_ip:$remote_port

	procd_set_param respawn

	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load mproxy
	config_foreach start_instance mproxy
}

service_triggers() {
	procd_add_reload_trigger "mproxy"
}
