#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.ATMaterial >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.ATMaterial=/luci-static/atmaterial
		set luci.main.mediaurlbase=/luci-static/atmaterial
		commit luci
	EOF
fi

exit 0
